version: "3"

services:
  cachet-baltha:
    image: cachet-baltha/docker
    environment:
      - CACHETHQ_DEBUG=${CACHETHQ_DEBUG}
      - CACHETHQ_APP_URL=${CACHETHQ_APP_URL}
      - CACHETHQ_APP_DEBUG=${CACHETHQ_APP_DEBUG}
      - CACHETHQ_GOOGLE_CLIENT_ID=${CACHETHQ_GOOGLE_CLIENT_ID}
      - CACHETHQ_GOOGLE_CLIENT_SECRET=${CACHETHQ_GOOGLE_CLIENT_SECRET}
      - CACHETHQ_GOOGLE_REDIRECT_URL=${CACHETHQ_GOOGLE_REDIRECT_URL}
      - CACHETHQ_GOOGLE_ENABLED_DOMAIN=${CACHETHQ_GOOGLE_ENABLED_DOMAIN}
      - CACHETHQ_DB_DRIVER=${CACHETHQ_DB_DRIVER}
      - CACHETHQ_DB_HOST=${CACHETHQ_DB_HOST}
      - CACHETHQ_DB_DATABASE=${CACHETHQ_DB_DATABASE}
      - CACHETHQ_DB_USERNAME=${CACHETHQ_DB_USERNAME}
      - CACHETHQ_DB_PASSWORD=${CACHETHQ_DB_PASSWORD}
      - CACHETHQ_DB_PORT=${CACHETHQ_DB_PORT}
    ports:
      - 8000:8000
    restart: always
  drhibbert:
    image: drhibbert
    ports:
      - 9000:80
    links:
      - cachet-baltha
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DRHIBBERT_CACHETCLIENT_TOKEN=DRHIBBERT_CACHETCLIENT_TOKEN}
      - DRHIBBERT_CACHETCLIENT_URL=${DRHIBBERT_CACHETCLIENT_URL}
#      - DRHIBBERT_AWS_TAG_MONITOR_GROUP_KEY=${DRHIBBERT_AWS_TAG_MONITOR_GROUP_KEY}
#      - DRHIBBERT_AWS_TAG_MONITOR_COMPONENT_KEY=${DRHIBBERT_AWS_TAG_MONITOR_COMPONENT_KEY}
      - DRHIBBERT_AWS_TOPICALARM=${DRHIBBERT_AWS_TOPICALARM}
#      - DRHIBBERT_AWS_PREFIX_ALARM=${DRHIBBERT_AWS_PREFIX_ALARM}
      - DRHIBBERT_NEWRELICCLIENT_TOKEN=${DRHIBBERT_NEWRELICCLIENT_TOKEN}
      - DRHIBBERT_NEWRELICCLIENT_URL=${DRHIBBERT_NEWRELICCLIENT_URL}
      - DRHIBBERT_NEWRELICCLIENT_CHANNEL_ID=${DRHIBBERT_NEWRELICCLIENT_CHANNEL_ID}
    depends_on:
      - cachet-baltha
    restart: always

